### ISSUE TITLE
Enhancement: include line numbers on prop_assert_eq!

### ISSUE THREAD

**Issue by boustrophedon** [AltSysrq/proptest#148]
https://github.com/AltSysrq/proptest/blob/09205111f14c462c4e4fc38161f28360e140e3ed/proptest/src/sugar.rs#L714

`prop_assert` includes the line numbers in the assertion but `prop_assert_eq` does not, which is important because otherwise the line number of the failure given by `cargo test` is just the line that says `proptest!`

If there is no reason why this shouldn't be the default, I'd be happy to submit a PR.

---

Additionally, it would be nice to have an optional dependency that does something like https://crates.io/crates/pretty-assertions - under the hood it just uses https://github.com/johannhof/difference.rs

if this is also something you think would be good to have, I would also be happy to work on that.

**Comment by AltSysrq** [comment]
Can you give an example where this happens? I can't see any obvious way to reproduce what you describe. `prop_assert_eq!` just delegates to `prop_assert!` which always includes the location, and in the output of the `dateparser_v2` example, both line numbers are present:

```
thread 'main' panicked at 'Test failed: assertion failed: `(left == right)` (left: `(0, 10, 1)`, right: `(0, 0, 1)`) at proptest/examples/dateparser_v2.rs:52; minimal failing input: y = 0, m = 10, d = 1                                                                                 
        successes: 1
        local rejects: 0
        global rejects: 0
', proptest/examples/dateparser_v2.rs:39:1
```

**Comment by boustrophedon** [comment]
Upon re-inpsection you're entirely right! I missed it because it was buried in-between the large arguments to assert_eq and the inputs:
 
```
thread 'sync::server::tests::sync::test_server_process_sync_three_clients_arb' panicked at 'Test failed: assertion failed: `(left == right)` (left: `[Add(Task { task: "a", priority: 1, reward: false, uuid: a62d083b-90da-44df-83d4-2bad0b7f03a9 })]`, right: `[]`) at src/sync/server/tests/sync.rs:210; minimal failing input: ops1 = [Add(Task { task: "a", priority: 1, reward: false, uuid: 70586e78-3fa7-4d67-a3ee-26f4a8933475 })], ops2 = [Add(Task { task: "0", priority: 1, reward: false, uuid: 11cea76a-415a-4daa-a51d-aac6e8c4451e })], ops3 = [Add(Task { task: " ", priority: 1, reward: false, uuid: 5c8d8aed-20e5-43bc-ad43-197d9d0d0ff8 })]
	successes: 0
	local rejects: 0
	global rejects: 0
', src/sync/server/tests/sync.rs:177:1
```

I wonder if there's a way to make it stand out more. Feel free to close this if not.

**Comment by AltSysrq** [comment]
std's `assert_eq!` now has line breaks between some of the items. I'm planning on duplicating that formatting here so hopefully that will make it clearer.

**Comment by AltSysrq** [comment]
0.9.4 incorporates the formatting change. I'm going to keep this issue open for now to consider your other suggestion.

**Comment by boustrophedon** [comment]
Thanks! Should I retitle the issue?

**Comment by AltSysrq** [comment]
Good idea. I edited the title, but feel free to change it to something else if you think of something better.
